# src/ota_installer/tasks/mappings/constants.py
from enum import Enum


class TaskGroup(Enum):
    PREPARATION = "preparation"
    MIGRATION = "migration"
    APPLICATION = "application"


class TaskName(Enum):
    EXTRACT_PAYLOAD_IMAGE = "EXTRACT_PAYLOAD_IMAGE"
    RENAME_PAYLOAD_IMAGE = "RENAME_PAYLOAD_IMAGE"
    EXTRACT_STOCK_BOOT_IMAGE = "EXTRACT_STOCK_BOOT_IMAGE"
    BACKUP_STOCK_BOOT_IMAGE = "BACKUP_STOCK_BOOT_IMAGE"
    CHECK_ADB_CONNECTION = "CHECK_ADB_CONNECTION"
    PUSH_STOCK_BOOT_IMAGE = "PUSH_STOCK_BOOT_IMAGE"
    FIND_PATCHED_BOOT_IMAGE = "FIND_PATCHED_BOOT_IMAGE"
    PULL_PATCHED_BOOT_IMAGE = "PULL_PATCHED_BOOT_IMAGE"
    REBOOT_TO_RECOVERY = "REBOOT_TO_RECOVERY"
    ADB_SIDELOAD = "ADB_SIDELOAD"
    REBOOT_TO_BOOTLOADER = "REBOOT_TO_BOOTLOADER"
    BOOT_MAGISK_IMAGE = "BOOT_MAGISK_IMAGE"

    @property
    def under_case(self) -> str:
        return self.value.lower()
